name: OMG_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.9.1
  - alsa-lib=1.2.8
  - appdirs=1.4.4
  - attr=2.5.1
  - attrs=22.2.0
  - autopage=0.5.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=2.116
  - blas-devel=3.9.0
  - bokeh=3.0.3
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bottleneck=1.3.6
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.0.4
  - cliff=4.1.0
  - cloudpickle=2.2.1
  - cmaes=0.9.1
  - cmd2=2.4.2
  - colorama=0.4.6
  - colorlog=6.7.0
  - contourpy=1.0.7
  - cryptography=39.0.0
  - cudatoolkit=11.1.74
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2021.9.1
  - dask-core=2021.9.1
  - dask-cuda=21.10.0
  - dbus=1.13.6
  - distributed=2021.9.1
  - expat=2.5.0
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - fsspec=2023.1.0
  - gettext=0.21.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - graphite2=1.3.13
  - greenlet=2.0.1
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.33
  - harfbuzz=6.0.0
  - heapdict=1.0.1
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.10.2
  - jack=1.9.21
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgpg-error=1.46
  - libhwloc=2.8.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libllvm15=15.0.7
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.1
  - libsndfile=1.2.0
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=252
  - libuuid=2.32.1
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - llvmlite=0.39.1
  - locket=1.0.0
  - lz4-c=1.9.3
  - mako=1.2.4
  - markupsafe=2.1.2
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpg123=1.31.2
  - msgpack-python=1.0.4
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.3
  - nspr=4.35
  - nss=3.82
  - numba=0.56.4
  - numexpr=2.8.3
  - numpy=1.21.2
  - openjpeg=2.5.0
  - openssl=3.0.7
  - optuna=2.10.1
  - packaging=23.0
  - pandas=1.3.5
  - partd=1.3.0
  - pbr=5.11.1
  - pcre2=10.40
  - pillow=9.4.0
  - pip=22.3.1
  - pixman=0.40.0
  - ply=3.11
  - pooch=1.6.0
  - prettytable=3.6.0
  - psutil=5.9.4
  - pthread-stubs=0.4
  - pulseaudio=16.1
  - pycairo=1.23.0
  - pycparser=2.21
  - pynvml=11.4.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyperclip=1.8.2
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.10.2
  - pytorch-mutex=1.0
  - pytz=2022.7.1
  - pyyaml=6.0
  - qt-main=5.15.6
  - rdkit=2021.09.4
  - readline=8.1.2
  - reportlab=3.6.12
  - requests=2.28.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - setuptools=66.1.1
  - sip=6.7.5
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlalchemy=1.4.46
  - sqlite=3.40.0
  - stevedore=4.1.1
  - tbb=2021.7.0
  - tblib=1.7.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.14
  - wcwidth=0.2.6
  - wheel=0.38.4
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2022.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zict=2.2.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
