name: OMG_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.3
  - attrs=21.4.0
  - blas=1.0
  - bokeh=2.4.3
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cairo=1.16.0
  - certifi=2022.9.24
  - cffi=1.15.0
  - click=8.0.4
  - cloudpickle=2.2.0
  - colorama=0.4.5
  - cryptography=35.0.0
  - cudatoolkit=11.1.74
  - cycler=0.11.0
  - cytoolz=0.11.2
  - dask=2021.9.1
  - dask-core=2021.9.1
  - dask-cuda=21.10.0
  - dbus=1.13.18
  - distributed=2021.9.1
  - expat=2.4.1
  - fftw=3.3.9
  - filelock=3.7.1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - fsspec=2022.10.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - greenlet=1.1.2
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - heapdict=1.0.1
  - icu=68.2
  - idna=3.3
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.68.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.15.8
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvorbis=1.3.7
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - llvmlite=0.36.0
  - locket=1.0.0
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msgpack-python=1.0.3
  - munkres=1.1.4
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - ncurses=6.3
  - nspr=4.32
  - nss=3.69
  - numba=0.53.1
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1o
  - packaging=21.3
  - pandas=1.3.5
  - partd=1.3.0
  - pcre=8.45
  - pillow=8.4.0
  - pip=21.2.4
  - pixman=0.40.0
  - psutil=5.9.1
  - pycairo=1.20.1
  - pycparser=2.21
  - pynvml=11.4.1
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.10.2
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pyyaml=6.0
  - qt=5.12.9
  - ray-core=1.6.0
  - ray-tune=1.6.0
  - rdkit=2021.09.4
  - readline=8.1.2
  - redis-py=3.5.3
  - reportlab=3.5.68
  - scipy=1.7.3
  - seaborn=0.11.2
  - setproctitle=1.1.10
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlalchemy=1.4.31
  - sqlite=3.37.0
  - tblib=1.7.0
  - tensorboardx=2.5.1
  - tk=8.6.11
  - toolz=0.12.0
  - tornado=6.1
  - tqdm=4.62.3
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - wheel=0.37.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.2
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zict=2.2.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - aiosignal==1.2.0
    - alembic==1.8.1
    - arrow==1.2.2
    - asttokens==2.0.5
    - astunparse==1.6.3
    - autopage==0.5.1
    - backcall==0.2.0
    - cachetools==5.0.0
    - cairocffi==1.3.0
    - cairosvg==2.5.2
    - charset-normalizer==2.0.11
    - cliff==3.10.1
    - cmaes==0.8.2
    - cmd2==2.4.2
    - colorlog==6.6.0
    - cssselect2==0.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - distlib==0.3.5
    - executing==0.8.3
    - fcd==1.1
    - flatbuffers==1.12
    - frozenlist==1.3.0
    - gast==0.4.0
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.43.0
    - h5py==3.7.0
    - importlib-metadata==4.10.1
    - ipython==8.3.0
    - jedi==0.18.1
    - joblib==1.1.0
    - jsonschema==4.7.2
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.1
    - mako==1.2.1
    - markdown==3.3.6
    - matplotlib-inline==0.1.3
    - multiset==3.0.1
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - optuna==2.10.1
    - parso==0.8.3
    - pbr==5.9.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==2.5.2
    - prettytable==3.3.0
    - prompt-toolkit==3.0.29
    - protobuf==3.19.4
    - ptyprocess==0.7.0
    - pubchempy==1.0.4
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.12.0
    - pyperclip==1.8.2
    - pyrsistent==0.18.1
    - ray==1.13.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-learn==1.0.2
    - sklearn==0.0
    - stack-data==0.2.0
    - stevedore==4.0.0
    - tabulate==0.8.9
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - traitlets==5.2.1.post0
    - urllib3==1.26.8
    - virtualenv==20.15.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.0.2
    - wrapt==1.14.1
    - zipp==3.7.0
